In [1]:
import os
import pandas as pd

In [2]:
folder_path = 'content/drive/My Drive'

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [14]:
file_path ='/content/drive/My Drive/Machine Learning/Praktikum1/data/day.csv'

In [15]:
df = pd.read_csv(file_path)

In [16]:
df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [17]:
df1 = df[['instant', 'dteday', 'season', 'temp', 'hum', 'windspeed']]
print(df1)

     instant      dteday  season      temp       hum  windspeed
0          1  2011-01-01       1  0.344167  0.805833   0.160446
1          2  2011-01-02       1  0.363478  0.696087   0.248539
2          3  2011-01-03       1  0.196364  0.437273   0.248309
3          4  2011-01-04       1  0.200000  0.590435   0.160296
4          5  2011-01-05       1  0.226957  0.436957   0.186900
..       ...         ...     ...       ...       ...        ...
726      727  2012-12-27       1  0.254167  0.652917   0.350133
727      728  2012-12-28       1  0.253333  0.590000   0.155471
728      729  2012-12-29       1  0.253333  0.752917   0.124383
729      730  2012-12-30       1  0.255833  0.483333   0.350754
730      731  2012-12-31       1  0.215833  0.577500   0.154846

[731 rows x 6 columns]

In [21]:
df1.to_csv("latihan01.csv", index=False)